name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt install -y libsdl2-dev libsdl2-ttf-dev
    - name: make
      run: make
